import type {
  CompanyInsights,
  ConversationSignal,
  DailyDigest,
  EntityRef,
  PersonRecommendation,
  ResearchJob,
} from "./types";

const now = new Date();
const iso = (daysAgo: number, hoursAgo = 0) =>
  new Date(now.getTime() - daysAgo * 86400000 - hoursAgo * 3600000).toISOString();

const people: PersonRecommendation[] = [
  {
    person_id: "p_dana_wu",
    name: "Dana Wu",
    email: "dana.wu@vantagerobotics.io",
    company_name: "Vantage Robotics",
    interest_level: "HIGH",
    urgency: "HIGH",
    sentiment: "POSITIVE",
    latest_next_action: "SEND_REPLY",
    latest_objections: null,
    latest_confidence: 0.91,
    last_signal_at: iso(0, 3),
    days_since_signal: 0.13,
    icp_score: 82,
    icp_priority: "HIGH",
    buying_intent_score: 94,
    temperature: "HOT",
    bucket: "CONTACT_TODAY",
    reason: "High interest, high urgency, replied 3h ago with positive sentiment.",
    best_message: "Dana asked for pricing on the enterprise tier -- send it before the window cools.",
  },
  {
    person_id: "p_marcus_ilori",
    name: "Marcus Ilori",
    email: "marcus@meridianhealth.com",
    company_name: "Meridian Health",
    interest_level: "HIGH",
    urgency: "MEDIUM",
    sentiment: "POSITIVE",
    latest_next_action: "SCHEDULE_FOLLOW_UP",
    latest_objections: "Needs SOC 2 report before legal will sign off.",
    latest_confidence: 0.86,
    last_signal_at: iso(1, 2),
    days_since_signal: 1.08,
    icp_score: 74,
    icp_priority: "HIGH",
    buying_intent_score: 81,
    temperature: "HOT",
    bucket: "CONTACT_TODAY",
    reason: "High interest, one open objection (compliance docs) blocking legal.",
    best_message: "Attach the SOC 2 report and propose a call with their security team this week.",
  },
  {
    person_id: "p_renee_castillo",
    name: "Renee Castillo",
    email: "renee.c@northwindlogistics.com",
    company_name: "Northwind Logistics",
    interest_level: "MEDIUM",
    urgency: "HIGH",
    sentiment: "MIXED",
    latest_next_action: "ESCALATE_TO_HUMAN",
    latest_objections: "Budget was reallocated to Q1; wants to revisit pricing.",
    latest_confidence: 0.72,
    last_signal_at: iso(0, 8),
    days_since_signal: 0.33,
    icp_score: 61,
    icp_priority: "MEDIUM",
    buying_intent_score: 68,
    temperature: "WARM",
    bucket: "CONTACT_TODAY",
    reason: "Urgent timeline but budget objection -- needs a human on pricing.",
    best_message: "Loop in sales leadership on a revised Q1 proposal before the urgency fades.",
  },
  {
    person_id: "p_theo_bergstrom",
    name: "Theo Bergstrom",
    email: "theo@fernbankanalytics.com",
    company_name: "Fernbank Analytics",
    interest_level: "MEDIUM",
    urgency: "LOW",
    sentiment: "NEUTRAL",
    latest_next_action: "SCHEDULE_FOLLOW_UP",
    latest_objections: null,
    latest_confidence: 0.64,
    last_signal_at: iso(3, 1),
    days_since_signal: 3.04,
    icp_score: 55,
    icp_priority: "MEDIUM",
    buying_intent_score: 47,
    temperature: "WARM",
    bucket: "MONITOR",
    reason: "Steady interest, no urgency signal -- worth a check-in, not a scramble.",
    best_message: "Send the case study Theo asked about and propose a follow-up next week.",
  },
  {
    person_id: "p_alina_petrova",
    name: "Alina Petrova",
    email: "alina@alderandco.com",
    company_name: "Alder & Co",
    interest_level: "LOW",
    urgency: "LOW",
    sentiment: "NEUTRAL",
    latest_next_action: "NO_ACTION",
    latest_objections: "Evaluating a competitor in parallel.",
    latest_confidence: 0.58,
    last_signal_at: iso(6, 4),
    days_since_signal: 6.17,
    icp_score: 39,
    icp_priority: "LOW",
    buying_intent_score: 22,
    temperature: "COLD",
    bucket: "MONITOR",
    reason: "Low interest, comparing alternatives -- keep on the radar, don't chase.",
    best_message: "Light-touch check-in: ask how the evaluation is going, no pressure.",
  },
  {
    person_id: "p_oscar_lindqvist",
    name: "Oscar Lindqvist",
    email: "oscar@basecampfoundry.com",
    company_name: "Basecamp Foundry",
    interest_level: "NONE",
    urgency: "LOW",
    sentiment: "NEGATIVE",
    latest_next_action: "MARK_LOST",
    latest_objections: "Went with a competitor.",
    latest_confidence: 0.9,
    last_signal_at: iso(11, 0),
    days_since_signal: 11.4,
    icp_score: 48,
    icp_priority: "LOW",
    buying_intent_score: 4,
    temperature: "COLD",
    bucket: "IGNORE",
    reason: "Explicitly went with a competitor -- nothing actionable today.",
    best_message: "No message needed. Mark the opportunity lost and revisit in a quarter.",
  },
  {
    person_id: "p_priya_nair",
    name: "Priya Nair",
    email: "priya.nair@vantagerobotics.io",
    company_name: "Vantage Robotics",
    interest_level: "MEDIUM",
    urgency: "MEDIUM",
    sentiment: "POSITIVE",
    latest_next_action: "SEND_REPLY",
    latest_objections: null,
    latest_confidence: 0.77,
    last_signal_at: iso(0, 20),
    days_since_signal: 0.83,
    icp_score: 82,
    icp_priority: "HIGH",
    buying_intent_score: 71,
    temperature: "WARM",
    bucket: "CONTACT_TODAY",
    reason: "Second contact at an already-hot account -- reinforce Dana's thread.",
    best_message: "Thank Priya for looping in and offer to bring both her and Dana onto one call.",
  },
];

export const fixtureDigest: DailyDigest = {
  generated_at: iso(0, 0),
  considered_count: people.length,
  contact_today: people.filter((p) => p.bucket === "CONTACT_TODAY").sort((a, b) => b.buying_intent_score - a.buying_intent_score),
  ignore: people.filter((p) => p.bucket === "IGNORE"),
  hot: people.filter((p) => p.temperature === "HOT"),
  cold: people.filter((p) => p.temperature === "COLD"),
  ranked_by_buying_intent: [...people].sort((a, b) => b.buying_intent_score - a.buying_intent_score),
  top_pick: [...people].sort((a, b) => b.buying_intent_score - a.buying_intent_score)[0],
};

export const fixturePeopleRefs: EntityRef[] = people.map((p) => ({
  id: p.person_id,
  name: p.name,
  companyName: p.company_name ?? undefined,
}));

export const fixtureCompanyRefs: EntityRef[] = [
  { id: "c_vantage", name: "Vantage Robotics" },
  { id: "c_meridian", name: "Meridian Health" },
  { id: "c_northwind", name: "Northwind Logistics" },
  { id: "c_fernbank", name: "Fernbank Analytics" },
  { id: "c_alder", name: "Alder & Co" },
  { id: "c_basecamp", name: "Basecamp Foundry" },
];

const signalsByPerson: Record<string, ConversationSignal[]> = {
  p_dana_wu: [
    {
      id: "cs_1",
      status: "COMPLETED",
      interestLevel: "HIGH",
      urgency: "HIGH",
      sentiment: "POSITIVE",
      objections: null,
      recommendedNextAction: "SEND_REPLY",
      recommendedReplyDraft:
        "Hi Dana -- great question. I've attached enterprise pricing and a rollout timeline based on your team size. Happy to walk through it live this week if useful.",
      recommendedFollowUpAt: null,
      confidence: 0.91,
      rawExcerpt: "This looks great -- what would enterprise pricing look like for a team our size?",
      modelUsed: "llama-3.3-70b-versatile",
      createdAt: iso(0, 3),
    },
    {
      id: "cs_2",
      status: "COMPLETED",
      interestLevel: "MEDIUM",
      urgency: "MEDIUM",
      sentiment: "POSITIVE",
      objections: "Wants to see a live demo before committing to a pilot.",
      recommendedNextAction: "SCHEDULE_FOLLOW_UP",
      recommendedReplyDraft: "Happy to set up a demo -- does Thursday afternoon work on your end?",
      recommendedFollowUpAt: iso(-2, 0),
      confidence: 0.83,
      rawExcerpt: "Could we see this in action before we go further?",
      modelUsed: "llama-3.3-70b-versatile",
      createdAt: iso(4, 1),
    },
  ],
  p_marcus_ilori: [
    {
      id: "cs_3",
      status: "COMPLETED",
      interestLevel: "HIGH",
      urgency: "MEDIUM",
      sentiment: "POSITIVE",
      objections: "Needs SOC 2 report before legal will sign off.",
      recommendedNextAction: "SCHEDULE_FOLLOW_UP",
      recommendedReplyDraft:
        "Hi Marcus -- attaching our current SOC 2 Type II report now. Want to get your security team on a short call to close out any remaining questions?",
      recommendedFollowUpAt: iso(-1, 0),
      confidence: 0.86,
      rawExcerpt: "We're interested but legal will need a SOC 2 report before we can move forward.",
      modelUsed: "llama-3.3-70b-versatile",
      createdAt: iso(1, 2),
    },
  ],
  p_theo_bergstrom: [
    {
      id: "cs_4",
      status: "COMPLETED",
      interestLevel: "MEDIUM",
      urgency: "LOW",
      sentiment: "NEUTRAL",
      objections: null,
      recommendedNextAction: "SCHEDULE_FOLLOW_UP",
      recommendedReplyDraft: "Sending over the case study now -- let's reconnect next week to talk through fit.",
      recommendedFollowUpAt: iso(-4, 0),
      confidence: 0.64,
      rawExcerpt: "Do you have a case study for a company our size?",
      modelUsed: "llama-3.3-70b-versatile",
      createdAt: iso(3, 1),
    },
  ],
};

export function getConversationSignals(personId: string): ConversationSignal[] {
  return signalsByPerson[personId] ?? [];
}

const researchJobsByCompany: Record<string, ResearchJob[]> = {
  c_vantage: [
    { id: "rj_1", status: "IMPORTED", source: "linkedin_harvest", sourceRunId: "run_2091", createdAt: iso(2, 0) },
    { id: "rj_2", status: "IMPORTED", source: "ddgs_search", sourceRunId: "run_2091", createdAt: iso(2, 0) },
    { id: "rj_3", status: "SKIPPED", source: "linkedin_harvest", sourceRunId: "run_1988", createdAt: iso(9, 0) },
  ],
  c_meridian: [
    { id: "rj_4", status: "IMPORTED", source: "ddgs_search", sourceRunId: "run_2077", createdAt: iso(5, 0) },
    { id: "rj_5", status: "FAILED", source: "linkedin_harvest", sourceRunId: "run_2077", createdAt: iso(5, 0) },
  ],
  c_northwind: [{ id: "rj_6", status: "IMPORTED", source: "ddgs_search", sourceRunId: "run_2050", createdAt: iso(8, 0) }],
};

export function getResearchJobs(companyId: string): ResearchJob[] {
  return researchJobsByCompany[companyId] ?? [];
}

const insightsByCompany: Record<string, CompanyInsights> = {
  c_vantage: {
    company_id: "c_vantage",
    company_name: "Vantage Robotics",
    latest_icp_score: 82,
    latest_icp_priority: "HIGH",
    last_enriched_at: iso(2, 0),
    icp_reasoning:
      "Series B robotics company, 140 employees, hiring aggressively for a role our product maps to directly. Strong technical champion engagement.",
    icp_rubric_version: "2024.3",
    research_job_count: 3,
    last_research_at: iso(2, 0),
    person_count: 2,
    people_by_interest_level: { HIGH: 1, MEDIUM: 1 },
    most_recent_signal_at: iso(0, 3),
    generated_at: iso(0, 0),
  },
  c_meridian: {
    company_id: "c_meridian",
    company_name: "Meridian Health",
    latest_icp_score: 74,
    latest_icp_priority: "HIGH",
    last_enriched_at: iso(5, 0),
    icp_reasoning: "Healthcare compliance requirements are heavy but budget and headcount fit is strong.",
    icp_rubric_version: "2024.3",
    research_job_count: 2,
    last_research_at: iso(5, 0),
    person_count: 1,
    people_by_interest_level: { HIGH: 1 },
    most_recent_signal_at: iso(1, 2),
    generated_at: iso(0, 0),
  },
  c_fernbank: {
    company_id: "c_fernbank",
    company_name: "Fernbank Analytics",
    latest_icp_score: null,
    latest_icp_priority: null,
    last_enriched_at: null,
    icp_reasoning: null,
    icp_rubric_version: null,
    research_job_count: 0,
    last_research_at: null,
    person_count: 1,
    people_by_interest_level: { MEDIUM: 1 },
    most_recent_signal_at: iso(3, 1),
    generated_at: iso(0, 0),
  },
};

export function getCompanyInsights(companyId: string): CompanyInsights {
  return (
    insightsByCompany[companyId] ?? {
      company_id: companyId,
      company_name: fixtureCompanyRefs.find((c) => c.id === companyId)?.name ?? companyId,
      latest_icp_score: null,
      latest_icp_priority: null,
      last_enriched_at: null,
      icp_reasoning: null,
      icp_rubric_version: null,
      research_job_count: 0,
      last_research_at: null,
      person_count: 0,
      people_by_interest_level: {},
      most_recent_signal_at: null,
      generated_at: iso(0, 0),
    }
  );
}
